spring.datasource.url=jdbc:mysql://localhost:3306/wonjaego
spring.datasource.username=root
spring.datasource.password=wonjaego1234

spring.jpa.hibernate.ddl-auto=update

wonjaego.storage.local.base-directory=data/product-photos
