spring.datasource.url=jdbc:h2:mem:wonjaego-test;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create

wonjaego.storage.local.base-directory=build/test-uploads
